import { library, dom, config } from '@fortawesome/fontawesome-svg-core';
// get list with ./infra/dev/find-font-awesome-icons.sh
// grep -riE 'fas' ./app   | grep -E 'fa(-[a-z]+)+' --only-matching | sort | uniq
import {
  faAngleLeft,
  faArrowCircleLeft,
  faArrowCircleRight,
  faArrowCircleUp,
  faBan,
  faBirthdayCake,
  faBus,
  faBuilding,
  faCalendarAlt,
  faCheck,
  faCheckCircle,
  faChevronCircleRight,
  faChevronDown,
  faChevronLeft,
  faChevronRight,
  faComments,
  faDownload,
  faDesktop,
  faExchangeAlt,
  faExclamationTriangle,
  faExternalLinkAlt,
  faEye,
  faEyeSlash,
  faFileAlt,
  faFilePdf,
  faHistory,
  faHourglassStart,
  faInfoCircle,
  faCopy,
  faLayerGroup,
  faMapMarker,
  faMapMarkerAlt,
  faMousePointer,
  faPen,
  faPhone,
  faPlus,
  faSortDown,
  faSortUp,
  faSpinner,
  faSquare as faSquareSolid,
  faQuestionCircle,
  faSchool,
  faSearch,
  faSignature,
  faSmile,
  faSuitcase,
  faTimes,
  faTrain,
  faTrash,
  faUniversalAccess,
  faUniversity,
  faUser,
  faUsers,
  faUserTie,
  faWalking
} from '@fortawesome/free-solid-svg-icons';

// get list with ./infra/dev/find-font-awesome-icons.sh
// grep -riE 'far' ./app   | grep -E 'fa(-[a-z]+)+' --only-matching | sort | uniq
import {
  faCircle,
  faEnvelope,
  faFlag,
  faHandshake,
  faSquare as faSquareRegular,
} from '@fortawesome/free-regular-svg-icons';

// avoid SVG flickering
// see: https://github.com/FortAwesome/Font-Awesome/issues/11924
config.mutateApproach = 'sync';
library.add(
  faAngleLeft,
  faArrowCircleLeft,
  faArrowCircleRight,
  faArrowCircleUp,
  faBan,
  faBirthdayCake,
  faBus,
  faBuilding,
  faCalendarAlt,
  faCheck,
  faCheckCircle,
  faChevronCircleRight,
  faChevronDown,
  faChevronLeft,
  faChevronRight,
  faCircle,
  faComments,
  faDownload,
  faDesktop,
  faEnvelope,
  faExchangeAlt,
  faExclamationTriangle,
  faExternalLinkAlt,
  faEye,
  faEyeSlash,
  faFlag,
  faFileAlt,
  faFilePdf,
  faHandshake,
  faHistory,
  faHourglassStart,
  faInfoCircle,
  faCopy,
  faLayerGroup,
  faMapMarker,
  faMapMarkerAlt,
  faMousePointer,
  faPen,
  faPhone,
  faPlus,
  faSortDown,
  faSortUp,
  faSpinner,
  faSquareRegular,
  faSquareSolid,
  faQuestionCircle,
  faSchool,
  faSearch,
  faSignature,
  faSmile,
  faSuitcase,
  faTimes,
  faTrain,
  faTrash,
  faUniversalAccess,
  faUniversity,
  faUser,
  faUsers,
  faUserTie,
  faWalking
);

// makes it works with Turbolink on document mutation
dom.watch({ observeMutationsRoot: document });
