# frozen_string_literal: true
namespace :data_migrations do
  desc 'Add accents and fix typos in group names'
  task migrate_group_names: :environment do
    groups_to_rename = [
      ['ELYSEE', "PRÉSIDENCE DE LA RÉPUBLIQUE"],
      ['MATIGNON', "PREMIER MINISTRE"],
      ["MINISTERE DE L'ACTION ET DES COMPTES PUBLICS", "MINISTÈRE DE L'ACTION ET DES COMPTES PUBLICS"],
      ["MINISTERE DE L'ECONOMIE ET DES FINANCES", "MINISTÈRE DE L'ÉCONOMIE ET DES FINANCES"],
      ['MINISTERE DE LA TRANSITION ECOLOGIQUE ET SOLIDAIRE', "MINISTÈRE DE LA TRANSITION ÉCOLOGIQUE ET SOLIDAIRE"],
      ['MINISTERE DES ARMEES', "MINISTÈRE DES ARMÉES"],
      ["MINISTERE DE L'AGRICULTURE ET DE L'ALIMENTATION", "MINISTÈRE DE L'AGRICULTURE ET DE L'ALIMENTATION"],
      ['MINISTERE DES SOLIDARITES ET DE LA SANTE', "MINISTÈRE DES SOLIDARITÉS ET DE LA SANTÉ"],
      ["MINISTERE DE L'INTERIEUR", "MINISTÈRE DE L'INTÉRIEUR"],
      ['MINITERE DE LA JUSTICE', "MINISTÈRE DE LA JUSTICE"],
      ['MINITERE DE LA CULTURE', "MINISTÈRE DE LA CULTURE"],
      ["MINISTERE DE L'EUROPE ET DES AFFAIRES ETRANGERES", "MINISTÈRE DE L'EUROPE ET DES AFFAIRES ÉTRANGÈRES"],
      ['MINISTERE DE LA COHESION DES TERRITOIRES', "MINISTÈRE DE LA COHÉSION DES TERRITOIRES ET DES RELATIONS AVEC LES COLLECTIVITÉS TERRITORIALES"],
      ["MINISTERE DE L'EDUCATION NATIONALE ET DE LA JEUNESSE", "MINISTÈRE DE L'ÉDUCATION NATIONALE ET DE LA JEUNESSE"],
      ['MINISTERE DES OUTRE-MER', "MINISTÈRE DES OUTRE-MER"]
    ]

    groups_to_rename.each do |group_to_rename|
      InternshipOffer.where(group: group_to_rename[0]).update_all(group: group_to_rename[1])
    end
  end
end
