import './favicon.png'
import './logo-mon-stage-3e.svg'
import './logo-beta-gouv-fr.png'

import './pages/logo_onisep.jpg'
import './pages/logo_cget_texte.png'

import './homepage/icon-documents-utiles.svg'
import './homepage/benefices/icon-accompagner-les-eleves.png'
import './homepage/benefices/icon-offrir-un-stage.png'
import './homepage/benefices/icon-trouver-un-stage.png'

import './homepage/partenaires/Logo-onisep.jpg'
import './homepage/partenaires/Logo-FACE.jpg'
import './homepage/partenaires/Logo-degunsanstage.jpg'
import './homepage/partenaires/Logo-jobIRL.jpg'
import './homepage/partenaires/Logo-le-reseau.jpg'
import './homepage/partenaires/Logo-les-entreprises-pour-la-cite.jpg'
import './homepage/partenaires/Logo-tous-en-stage.jpg'
import './homepage/partenaires/Logo-un-stage-et-apres.jpg'
import './homepage/partenaires/Logo-viens-voir-mon-taf.jpg'
import './homepage/partenaires/Logo-jndj.png'
import './homepage/partenaires/Logo-united-way.png'

import './homepage/sponsors/Logo-MCTRCT-CGET.png'
import './homepage/sponsors/Logo-ministere-education-nationale.png'

import './documents-utiles/CarnetStagePro_USEA_WEB-2.jpg'
import './documents-utiles/RienNeSertDeCourirPageBD.jpg'
import './documents-utiles/USEA-Carnet-Stage-Education.jpg'
import './documents-utiles/USEA-Cherchez-la-chercheuse.jpg'
import './documents-utiles/versLinfini.jpg'
