# frozen_string_literal: true

class OldGroup
  PUBLIC = [
    'PRÉSIDENCE DE LA RÉPUBLIQUE',
    'PREMIER MINISTRE',
    "MINISTÈRE DE L'ACTION ET DES COMPTES PUBLICS",
    "MINISTÈRE DE L'ÉCONOMIE ET DES FINANCES",
    'MINISTÈRE DE LA TRANSITION ÉCOLOGIQUE ET SOLIDAIRE',
    'MINISTÈRE DES ARMÉES',
    "MINISTÈRE DE L'AGRICULTURE ET DE L'ALIMENTATION",
    'MINISTÈRE DES SOLIDARITÉS ET DE LA SANTÉ',
    "MINISTÈRE DE L'INTÉRIEUR",
    'MINISTÈRE DE LA JUSTICE',
    'MINISTÈRE DE LA CULTURE',
    "MINISTÈRE DE L'EUROPE ET DES AFFAIRES ÉTRANGÈRES",
    'MINISTÈRE DE LA COHÉSION DES TERRITOIRES ET DES RELATIONS AVEC LES COLLECTIVITÉS TERRITORIALES',
    "MINISTÈRE DE L'ÉDUCATION NATIONALE ET DE LA JEUNESSE",
    "MINISTÈRE DE L'ENSEIGNEMENT SUPÉRIEUR, DE LA RECHERCHE ET DE L'INNOVATION",
    'MINISTÈRE DES OUTRE-MER',
    'MINISTÈRE DU TRAVAIL',
    "MINISTÈRE DES SPORTS",
    "CONSEIL RÉGIONAL",
    "CONSEIL DÉPARTEMENTAL",
    "MAIRIE",
    "PRÉFECTURE",
    "CAISSE PRIMAIRE D’ASSURANCE MALADIE",
    "CAISSE D'ALLOCATIONS FAMILIALES",
    "PÔLE EMPLOI",
    "RATP",
    "SNCF",
    "BANQUE DE FRANCE"
  ].sort.freeze
  PRIVATE = [
    'Accenture',
    'AccorHotels',
    'Adecco Group',
    'Afep',
    'Air France',
    'Amundi',
    "AUXI'LIFE",
    'AXA',
    'BIC',
    'BNP Paribas',
    'Bosch',
    'BPCE',
    'Bpifrance',
    'CA Brie Picardie',
    'CA Centre Est',
    'Carrefour',
    'CNP',
    'Coca-Cola European Partners France',
    'Coca-Cola France',
    'COMERSO',
    'Crédit Mutuel - CIC',
    'E. Leclerc',
    'Elior',
    'Engie',
    'EPSA',
    'FDJ',
    'FFB',
    'Fives',
    'FRTP',
    'Generali',
    'Genfit',
    'Groupe Sémaphores',
    'Groupe SKF',
    'Groupe Vicat',
    'GTT',
    'Guerbet',
    'Henkel',
    'Icade',
    'ICF Habitat',
    'Inditex',
    'Klépierre',
    'Korian',
    'Korn Ferry',
    'La Poste',
    "L'Oréal",
    'Louvre Hotels Group',
    'ManpowerGroup',
    'Michelin',
    'O2',
    'Ostrum Asset Management',
    'PROACTIVE ACADEMY',
    'Procter & Gamble',
    'Recyc-Matelas Europe',
    'Safran',
    'Saguez & Partners',
    'Sanofi',
    'Schneider Electric',
    'Shell',
    'Siemens',
    'Sodexo',
    'Starbucks',
    'Suez',
    'SWEN Capital Partners',
    'Système U',
    'Unibail-Rodamco-Westfield',
    'Valeo',
    'Vivendi',
    'Orange',
    'Crédit agricole'
  ].sort.freeze
end
