clevercloud:
  service: S3
  access_key_id: <%= ENV.fetch('CELLAR_ADDON_KEY_ID') %>
  secret_access_key: <%= ENV.fetch('CELLAR_ADDON_KEY_SECRET') %>
  region: 'us-west-1'
  bucket: <%= ENV['CELLAR_ADDON_BUCKET_NAME'] %>
  endpoint: <%= ENV.fetch('CELLAR_ADDON_ENDPOINT') %>
  force_path_style: true


local:
  service: Disk
  root: <%= Rails.root.join("storage/tmp/signatures") %>
