#!/bin/bash
# usage: copy this file to .git/hooks/pre-commit
set -x
command -v circleci >/dev/null 2>&1 || { echo "Git pre-commit must check circleci cli file before push ; please install it"; exit 1; }

circleci config validate .circleci/config.yml
if [ $? -ne 0 ]; then
	echo "Circle ci file not valid!"
  exit 1;
fi

rails test:system -- --fail-fast
if [ $? -ne 0 ]; then
  echo "System test failed!"
  exit 1;
fi;

exit 0
